# Generated by Django 4.2.13 on 2025-05-21 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petrochem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Electric_Generator',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('status_1', models.CharField(blank=True, max_length=50, null=True)),
                ('rpt_dt', models.CharField(blank=True, max_length=50, null=True)),
                ('ent_id', models.CharField(blank=True, max_length=50, null=True)),
                ('ent_name', models.CharField(blank=True, max_length=50, null=True)),
                ('plnt_id', models.CharField(blank=True, max_length=50, null=True)),
                ('plnt_nm', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('county', models.CharField(blank=True, max_length=50, null=True)),
                ('balauth', models.CharField(blank=True, max_length=50, null=True)),
                ('sector', models.CharField(blank=True, max_length=50, null=True)),
                ('gen_id', models.CharField(blank=True, max_length=50, null=True)),
                ('npl_cap_mw', models.CharField(blank=True, max_length=50, null=True)),
                ('techn', models.CharField(blank=True, max_length=50, null=True)),
                ('egy_src', models.CharField(blank=True, max_length=50, null=True)),
                ('prm_mvr', models.CharField(blank=True, max_length=50, null=True)),
                ('opr_mo', models.CharField(blank=True, max_length=50, null=True)),
                ('opr_yr', models.CharField(blank=True, max_length=50, null=True)),
                ('pln_mo', models.CharField(blank=True, max_length=50, null=True)),
                ('pln_yr', models.CharField(blank=True, max_length=50, null=True)),
                ('retr_mo', models.CharField(blank=True, max_length=50, null=True)),
                ('retr_yr', models.CharField(blank=True, max_length=50, null=True)),
                ('status_2', models.CharField(blank=True, max_length=50, null=True)),
                ('lat', models.CharField(blank=True, max_length=50, null=True)),
                ('long', models.CharField(blank=True, max_length=50, null=True)),
                ('x', models.CharField(blank=True, max_length=50, null=True)),
                ('y', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': '"eia"."electric_generator"',
                'managed': False,
            },
        ),
    ]
