# Generated by Django 5.1.7 on 2025-04-15 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petrochem', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pipeline_crudeoil',
            table='"pipelines"."crudeoil"',
        ),
        migrations.AlterModelTable(
            name='pipeline_fractracker',
            table='"pipelines"."fractracker"',
        ),
        migrations.AlterModelTable(
            name='pipeline_hgl',
            table='"pipelines"."hgl"',
        ),
        migrations.AlterModelTable(
            name='pipeline_naturalgas',
            table='"pipelines"."naturalgas"',
        ),
        migrations.AlterModelTable(
            name='pipeline_petroleum',
            table='"pipelines"."petroleum"',
        ),
    ]
