# Generated by Django 4.2.13 on 2025-05-21 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petrochem', '0002_electric_generator'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='electric_generator',
            table='"eia"."electric_generator_inventory_860m"',
        ),
    ]
