# Generated by Django 4.2.13 on 2025-05-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petrochem', '0004_plants_biodiesel_plants_ethanol_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plants_Coal',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('objectid', models.IntegerField()),
                ('plant_code', models.IntegerField()),
                ('plant_name', models.CharField(blank=True, max_length=50, null=True)),
                ('utility_id', models.IntegerField()),
                ('utility_name', models.CharField(blank=True, max_length=50, null=True)),
                ('sector_name', models.CharField(blank=True, max_length=50, null=True)),
                ('street_address', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('county', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('zip', models.IntegerField()),
                ('primsource', models.CharField(blank=True, max_length=50, null=True)),
                ('source_desc', models.CharField(blank=True, max_length=50, null=True)),
                ('tech_desc', models.CharField(blank=True, max_length=50, null=True)),
                ('install_mw', models.CharField(blank=True, max_length=50, null=True)),
                ('total_mw', models.CharField(blank=True, max_length=50, null=True)),
                ('bat_mw', models.CharField(blank=True, max_length=50, null=True)),
                ('bio_mw', models.CharField(blank=True, max_length=50, null=True)),
                ('coal_mw', models.CharField(blank=True, max_length=50, null=True)),
                ('geo_mw', models.CharField(blank=True, max_length=50, null=True)),
                ('hydro_mw', models.CharField(blank=True, max_length=50, null=True)),
                ('hydrops_mw', models.CharField(blank=True, max_length=50, null=True)),
                ('ng_mw', models.CharField(blank=True, max_length=50, null=True)),
                ('nuclear_mw', models.CharField(blank=True, max_length=50, null=True)),
                ('crude_mw', models.CharField(blank=True, max_length=50, null=True)),
                ('solar_mw', models.CharField(blank=True, max_length=50, null=True)),
                ('wind_mw', models.CharField(blank=True, max_length=50, null=True)),
                ('other_mw', models.CharField(blank=True, max_length=50, null=True)),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
                ('period', models.CharField(blank=True, max_length=50, null=True)),
                ('longitude', models.CharField(blank=True, max_length=50, null=True)),
                ('latitude', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': '"eia"."powerplants_coal"',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Powerplants_Coal',
        ),
    ]
