# Generated by Django 4.2.13 on 2025-07-01 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petrochem', '0006_plants_geothermal_plants_hydroelectric_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserve_Petroleum',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('objectid', models.IntegerField()),
                ('company', models.CharField(blank=True, max_length=50, null=True)),
                ('site', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('padd', models.IntegerField()),
                ('heatingoil_storage', models.IntegerField()),
                ('other_storage', models.IntegerField()),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
                ('period', models.CharField(blank=True, max_length=50, null=True)),
                ('longitude', models.CharField(blank=True, max_length=50, null=True)),
                ('latitude', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': '"eia"."reserves_petroleum"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Storage_Naturalgas',
            fields=[
                ('ftid', models.IntegerField()),
                ('objectid', models.IntegerField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fld_code', models.IntegerField()),
                ('res_code', models.IntegerField()),
                ('field', models.CharField(blank=True, max_length=50, null=True)),
                ('reservoir', models.CharField(blank=True, max_length=50, null=True)),
                ('field_type', models.CharField(blank=True, max_length=50, null=True)),
                ('company', models.CharField(blank=True, max_length=50, null=True)),
                ('county', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('region', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('base_gas', models.IntegerField()),
                ('work_cap', models.IntegerField()),
                ('fld_cap', models.IntegerField()),
                ('maxdeliv', models.IntegerField()),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
                ('period', models.CharField(blank=True, max_length=50, null=True)),
                ('longitude', models.CharField(blank=True, max_length=50, null=True)),
                ('latitude', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': '"eia"."undergroundstorage_naturalgas"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Terminal_Crudeoil',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fid', models.IntegerField()),
                ('site_name', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('padd', models.IntegerField()),
                ('station_ty', models.CharField(blank=True, max_length=50, null=True)),
                ('facility_t', models.CharField(blank=True, max_length=50, null=True)),
                ('handling', models.CharField(blank=True, max_length=50, null=True)),
                ('longitude', models.CharField(blank=True, max_length=50, null=True)),
                ('latitude', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': '"eia"."terminals_crudeoil_rail"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Terminal_Lng',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('objectid', models.IntegerField()),
                ('facility', models.CharField(blank=True, max_length=50, null=True)),
                ('owner', models.CharField(blank=True, max_length=50, null=True)),
                ('operator', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('county', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('functions', models.CharField(blank=True, max_length=50, null=True)),
                ('regas_bcfd', models.CharField(blank=True, max_length=50, null=True)),
                ('stora_bcf', models.CharField(blank=True, max_length=50, null=True)),
                ('liq_baseload_bcfd', models.CharField(blank=True, max_length=50, null=True)),
                ('liq_peak_bcfd', models.CharField(blank=True, max_length=50, null=True)),
                ('period', models.CharField(blank=True, max_length=50, null=True)),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
                ('latitude', models.CharField(blank=True, max_length=50, null=True)),
                ('longitude', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': '"eia"."terminals_lng"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Terminal_Petroleum',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('objectid', models.IntegerField()),
                ('company', models.CharField(blank=True, max_length=50, null=True)),
                ('site', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('padd', models.IntegerField()),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
                ('period', models.CharField(blank=True, max_length=50, null=True)),
                ('longitude', models.CharField(blank=True, max_length=50, null=True)),
                ('latitude', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': '"eia"."terminals_petroleum"',
                'managed': False,
            },
        ),
    ]
