# Generated by Django 5.0.7 on 2025-08-04 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petrochem', '0007_reserve_petroleum_storage_naturalgas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fertilizer_Plant',
            fields=[
                ('id', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
                ('company', models.CharField(blank=True, db_column='company', max_length=250, null=True)),
                ('fertilizer', models.CharField(blank=True, db_column='fertilizer', max_length=250, null=True)),
                ('town', models.CharField(blank=True, db_column='town', max_length=250, null=True)),
                ('state', models.CharField(blank=True, db_column='state', max_length=250, null=True)),
                ('latitude', models.FloatField(blank=True, db_column='latitude', null=True)),
                ('longitude', models.FloatField(blank=True, db_column='longitude', null=True)),
                ('status', models.CharField(blank=True, db_column='status', max_length=250, null=True)),
                ('nitrogen_f', models.FloatField(blank=True, db_column='nitrogen_f', null=True)),
                ('anyhdrousa', models.FloatField(blank=True, db_column='anyhdrousa', null=True)),
                ('grossammon', models.FloatField(blank=True, db_column='grossammon', null=True)),
                ('ammonia_bo', models.FloatField(blank=True, db_column='ammonia_bo', null=True)),
                ('ammoniasto', models.CharField(blank=True, db_column='ammoniasto', max_length=250, null=True)),
                ('netammonia', models.CharField(blank=True, db_column='netammonia', max_length=250, null=True)),
                ('uan_thousa', models.CharField(blank=True, db_column='uan_thousa', max_length=250, null=True)),
                ('uanstorage', models.CharField(blank=True, db_column='uanstorage', max_length=250, null=True)),
                ('urea_thous', models.FloatField(blank=True, db_column='urea_thous', null=True)),
                ('ureastorag', models.CharField(blank=True, db_column='ureastorag', max_length=250, null=True)),
                ('other_thou', models.CharField(blank=True, db_column='other_thou', max_length=250, null=True)),
                ('mmbtu_cons', models.CharField(blank=True, db_column='mmbtu_cons', max_length=250, null=True)),
                ('mcf_consum', models.CharField(blank=True, db_column='mcf_consum', max_length=250, null=True)),
                ('phosphoric', models.CharField(blank=True, db_column='phosphoric', max_length=250, null=True)),
                ('phosphor_1', models.FloatField(blank=True, db_column='phosphor_1', null=True)),
                ('processed', models.CharField(blank=True, db_column='processed_', max_length=250, null=True)),
                ('ammonium_u', models.CharField(blank=True, db_column='ammonium_u', max_length=250, null=True)),
                ('processed1', models.CharField(blank=True, db_column='processed1', max_length=250, null=True)),
                ('ammonium_1', models.CharField(blank=True, db_column='ammonium_1', max_length=250, null=True)),
                ('capacity_m', models.CharField(blank=True, db_column='capacity_m', max_length=250, null=True)),
                ('production', models.CharField(blank=True, db_column='production', max_length=250, null=True)),
                ('reserve_mi', models.CharField(blank=True, db_column='reserve_mi', max_length=250, null=True)),
                ('mmbtu_mill', models.CharField(blank=True, db_column='mmbtu_mill', max_length=250, null=True)),
                ('mcf_millio', models.CharField(blank=True, db_column='mcf_millio', max_length=250, null=True)),
                ('provenpeak', models.CharField(blank=True, db_column='provenpeak', max_length=250, null=True)),
                ('operationa', models.CharField(blank=True, db_column='operationa', max_length=250, null=True)),
                ('oremined_m', models.CharField(blank=True, db_column='oremined_m', max_length=250, null=True)),
                ('finishedpr', models.CharField(blank=True, db_column='finishedpr', max_length=250, null=True)),
                ('reserves_m', models.CharField(blank=True, db_column='reserves_m', max_length=250, null=True)),
                ('potashmine', models.CharField(blank=True, db_column='potashmine', max_length=250, null=True)),
                ('mmbtu_mi_1', models.CharField(blank=True, db_column='mmbtu_mi_1', max_length=250, null=True)),
                ('mcf_mill_1', models.CharField(blank=True, db_column='mcf_mill_1', max_length=250, null=True)),
                ('latitude1', models.FloatField(blank=True, db_column='latitude1', null=True)),
                ('longitude1', models.FloatField(blank=True, db_column='longitude1', null=True)),
                ('nitric_aci', models.FloatField(blank=True, db_column='nitric_aci', null=True)),
                ('liquid_nit', models.FloatField(blank=True, db_column='liquid_nit', null=True)),
                ('f41', models.FloatField(blank=True, db_column='f41', null=True)),
                ('ammonia_pe', models.CharField(blank=True, db_column='ammonia_pe', max_length=250, null=True)),
                ('nitrogenpr', models.CharField(blank=True, db_column='nitrogenpr', max_length=250, null=True)),
                ('links', models.CharField(blank=True, db_column='links', max_length=250, null=True)),
            ],
            options={
                'db_table': '"fta"."fertilizer_plants"',
                'managed': False,
            },
        ),
    ]
