# Generated by Django 5.0.7 on 2025-08-28 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petrochem', '0008_fertilizer_plant'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fertilizer_plant',
            table='"misc"."photos"',
        ),
    ]
