# Generated by Django 5.0.7 on 2025-08-28 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petrochem', '0009_alter_fertilizer_plant_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, db_column='title', max_length=2048, null=True)),
                ('date_taken', models.CharField(blank=True, db_column='date_taken', max_length=2048, null=True)),
                ('mission_desc', models.CharField(blank=True, db_column='mission_description', max_length=2048, null=True)),
                ('album', models.CharField(blank=True, db_column='albumtitle', max_length=2048, null=True)),
                ('description', models.CharField(blank=True, db_column='description', max_length=2048, null=True)),
                ('photo_src_url', models.CharField(blank=True, db_column='photo_src_url', max_length=2048, null=True)),
                ('latitude', models.FloatField(blank=True, db_column='latitude', null=True)),
                ('longitude', models.FloatField(blank=True, db_column='longitude', null=True)),
            ],
            options={
                'db_table': '"misc"."photos"',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='fertilizer_plant',
            table='"fta"."fertilizer_plants"',
        ),
    ]
