# Generated by Django 5.1.7 on 2026-05-14 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petrochem', '0010_photos_alter_fertilizer_plant_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='compressors',
            table='"portal_petrochem"."compressor_stations"',
        ),
    ]
